/*! \file productcnfg.h \brief product configuration file. */
// ****************************************************************************
//
//                      MSI ScaleCore
//
//                  Copyright (c) 2010 by
//            Measurement Systems International
//                   Seattle, Washington
//                   All Rights Reserved
//
// Filename: productdef.h
// Hardware: ATMEL AVR series
// OS:       independent
// Compiler: avr-gcc
// Software layer:  project wide
//
//  History:  Created on 2010-11-18 by Wai Fai Chin
//  History:  Modified on 2011-12-13 by Denis Monteiro
//
/// \code #include "productcnfg.h" \endcode
/// \par Overview
///     This file is generated by makefile based on a specified TARGET product.
///		It is in turn use by the compiler to generate a correct version of product specific software.
//
// ****************************************************************************
//@{

#ifndef MSI_PRODUCTCNFG_H
#define MSI_PRODUCTCNFG_H

#include "productdef.h"

#define CONFIG_PRODUCT_AS			CONFIG_AS_PORTAWEIGH2

#define CONFIG_SUBPRODUCT_AS		CONFIG_AS_PORTAWEIGH2_IS

#endif
//@}
